---
- name: Provision prototype application
  hosts: all
  become: true

  tasks:
  - name: Add Docker GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present

  - name: Add Docker APT repository
    apt_repository:
      repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
      state: present

  - name: Install Docker engine
    apt:
      name: docker-ce
      state: latest

  - name: Ensure Docker service is running and enabled
    service:
      name: docker
      state: started
      enabled: yes

  - name: Run containers
    shell:
      cmd: "docker compose -f docker-compose.yml up -d"
      chdir: /vagrant/

